RecycleBin/RecycleBin/Models/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Cryptography.X509Certificates;
using System.Web;
using DataAnnotationsValidations.Attributes;
using RecycleBin.Manager.Manager;
using RecycleBin.Model.Model;

namespace RecycleBin.Models
{
    public class CategoryViewModel
    {
        

        public int Id { get; set; }

        [Required(ErrorMessage = "Please Enter Category Code")]
        [MaxLength(4, ErrorMessage = "Must be 4 charecter")]
        [MinLength(4, ErrorMessage = "Must be 4 charecter")]
        [Display(Name = "Code")]
        [CustomValidation.checkUniqe(ErrorMessage = "Code Already Exist")]
        public string Code { get; set; }

        [Required(ErrorMessage = "Please Enter Category Name")]
        [MaxLength(30,ErrorMessage = "Maximum 30 charecter")]
        public string Name { get; set; }

        public List<Product> Products { get; set; }

        public List<Category> Categories { get; set; }

        public CategoryViewModel()
        {
            Categories = new List<Category>();
        }
    }

}

RecycleBin/RecycleBin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using RecycleBin.Manager.Manager;
using RecycleBin.Model.Model;
using RecycleBin.Models;

namespace RecycleBin.Controllers
{
    public class CategoryController : Controller
    {
        CategoryManager _categoryManager = new CategoryManager();

        // GET: Category
        public ActionResult Index()
        {

            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            CategoryViewModel categoryViewModel = new CategoryViewModel();
            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);
        }

        [HttpPost]
        public ActionResult Add(CategoryViewModel categoryViewModel)
        {
            Category category = Mapper.Map<Category>(categoryViewModel);
            string message = "";

            if (ModelState.IsValid)
            {
                if (_categoryManager.Add(category))
                {
                    message = "Saved";
                }
                else
                {
                    message = "Not Saved..!";
                }
            }
            else
            {
                ViewBag.Message = "Model State Failed..!";
            }

            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            Category category = _categoryManager.GetById(id);


            CategoryViewModel categoryViewModel = Mapper.Map<CategoryViewModel>(category);

            return View(categoryViewModel);

        }


        [HttpPost]
        public ActionResult Edit(CategoryViewModel categoryViewModel)
        {
            Category category = Mapper.Map<Category>(categoryViewModel);
            string message = "";
            if (ModelState.IsValid)
            {
                if (_categoryManager.Upadate(category))
                {
                    message = "Updated Successfully...!";
                }
                else
                {
                    message = "Not Updated...!";
                }
            }
            else
            {
                ViewBag.Message = "Model state failed..!";
            }
            categoryViewModel.Categories = _categoryManager.GetAll();
            return View(categoryViewModel);
            
        }

        public JsonResult IsCodeExist(string code)
        {
            var result = _categoryManager.GetAll();
                
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

RecycleBin/RecycleBin/Views/Shared/Category/_categoryDetails.cshtml
@model RecycleBin.Models.CategoryViewModel

<div class="row">
    <div class="col-lg-12">
        <div class="text-center">
            <h4>Available Categories</h4>
        </div>
        <div class="row">
            <div class="col-lg-8"></div>
            <div class="col-lg-4 form-group">
                <div class="input-group custom-search-form">
                    <input id="myInput" type="text" class="form-control" placeholder="Search by Name or Code">
                    <span class="input-group-btn">
                        <button class="btn btn-info" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
            <br/>
        </div>
      <div class="row"></div>
        <div class="adv-table">
            <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="myTable">
                <thead>
                <tr>
                    <th>SL</th>
                    <th>Code</th>
                    <th>Name</th>
                    <th>Action</th>
                </tr>
                </thead>
                @{ int sl = 0;}
                <tbody>
                @foreach (var category in Model.Categories)
                {
                    <tr>
                        <td>@(++sl)</td>
                        <td>@category.Code</td>
                        <td>@category.Name</td>
                        <td>@Html.ActionLink("Edit", "Edit", "Category", new { id = category.Id }, null)</td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.8.0.min.js"></script>
<script>
    $(document).ready(function(){
        $("#myInput").on("keyup", function() {
            var value = $(this).val().toLowerCase();
            $("#myTable tbody tr").filter(function() {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>