RecycleBin/RecycleBin/Models/SalesViewModel.cs
using RecycleBin.Model.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RecycleBin.Models
{
    public class SalesViewModel
    {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public string BillNo { get; set; }

        [Display(Name = "Available Quantity")]
        public int AvailableQuantity { get; set; }

        [Range(1,Int32.MaxValue, ErrorMessage = "Invalid Quantity")]
        public int Quantity { get; set; }

        [Display(Name = "M.R.P (TK.)")]
        public double MRP { get; set; }

        [Display(Name = "Total M.R.P (TK.)")]
        public double TotalMRP { get; set; }

        [Display(Name = "Grand Total")]
        public double GrandTotal { get; set; }

        [Display(Name = "Discount (%)")]
        public double DiscountPercentage { get; set; }

        [Display(Name = "Discount Ammount")]
        public double DiscountAmmount { get; set; }

        [Display(Name = "Payable Ammount")]
        public double PayableAmmount { get; set; }

        [Display(Name = "Customer")]
        public int CustomerId { get; set; }
        public Customer Customer { get; set; }

        [Display(Name = "Loyalty Point")]
        public double LoyalityPoint { get; set; }

        [Display(Name = "Category")]
        public int CategoryId { get; set; }
        public Category Category { get; set; }

        [Display(Name = "Product")]
        public int ProductId { get; set; }
        public Product Product { get; set; }

        public int SalesId { get; set; }
        public List<Sales> Saleses { get; set; }
        public List<SalesView> SalesViews = new List<SalesView>();

        public IEnumerable<SelectListItem> CustomerSelectListItems { get; set; }
        public IEnumerable<SelectListItem> CategorySelectListItems { get; set; }
        public IEnumerable<SelectListItem> ProductSelectListItems { get; set; }

        public List<SalesDetails> SalesDetailses { get; set; }

    }
}

RecycleBin/RecycleBin/Controllers/SalesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RecycleBin.Manager.Manager;
using RecycleBin.Model.Model;
using RecycleBin.Models;

namespace RecycleBin.Controllers
{
    public class SalesController : Controller
    {

        CustomerManager _customerManager = new CustomerManager();
        CategoryManager _categoryManager = new CategoryManager();
        ProductManager _productManager = new ProductManager();
        SalesManager _salesManager = new SalesManager();

        // GET: Sales
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            SalesViewModel salesViewModel = new SalesViewModel();
            salesViewModel.CustomerSelectListItems = _customerManager
                                                    .GetAll()
                                                    .Select(c => new SelectListItem()
                                                        {
                                                            Value = c.Id.ToString(),
                                                            Text = c.Name
                                                        }
                                                    ).ToList();

            salesViewModel.CategorySelectListItems = _categoryManager
                                                    .GetAll()
                                                    .Select(c => new SelectListItem()
                                                        {
                                                            Value = c.Id.ToString(),
                                                            Text = c.Name
                                                        }
                                                    ).ToList();

            
            return View(salesViewModel);
        }

        [HttpPost]
        public void Add(Sales sales)
        {
            string message = "";

            if (_salesManager.Add(sales))
            {
                message = "Sales Completed Successfully";
            }
            else
            {
                message = "Failed";
            }

            ViewBag.Message = message;

            Add();
        }

        [HttpGet]
        public ActionResult ViewSalesReport()
        {
            SalesViewModel salesViewModel = new SalesViewModel();
            salesViewModel.Saleses = _salesManager.GetAll();

            return View(salesViewModel);
        }
        [HttpGet]
        public PartialViewResult ViewSalesDetails(int salesId)
        {
            SalesViewModel salesViewModel = new SalesViewModel();
            Sales sales = new Sales();
            sales = _salesManager.GetSalesById(salesId);

            salesViewModel.Date = sales.Date;
            salesViewModel.Customer = sales.Customer;
            salesViewModel.DiscountPercentage = sales.DiscountPercentage;
            salesViewModel.SalesDetailses = _salesManager.GetSalesDetailsesById(salesId);
            return PartialView("ViewSalesDetails", salesViewModel);
        }

        public JsonResult GetProductByCategoryId(int categoryId)
        {
            var productList = _productManager
                .GetAll()
                .Where(c => c.CategoryId == categoryId)
                .Select(c => new
                {
                    c.Id,
                    c.Name
                });

            return Json(productList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetCustomerDetailsById(int customerId)
        {
            Customer customer = _customerManager.GetById(customerId);

            return Json(customer, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProductDetailsById(int productId)
        {
            Product product = _productManager.GetById(productId);

            return Json(product, JsonRequestBehavior.AllowGet);
        }

        public JsonResult UpdateCustomer(int customerId, int point)
        {
            Customer cus = _customerManager.GetById(customerId);
            cus.LoyalityPoint = point;
            _customerManager.Upadate(cus);
            return Json(0, JsonRequestBehavior.AllowGet);
        }
    }
}

RecycleBin/RecycleBin/Views/Sales/ViewSalesDetails.cshtml
@model RecycleBin.Models.SalesViewModel

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="text-center"><h3>Sales Details</h3></div>

<div class="adv-table">
    <table>
        <tbody>
            <tr>
                <td>Date </td>
                <td> :</td>
                <td>@Model.Date.ToShortDateString()</td>
            </tr>
            <tr>
                <td>Customer</td>
                <td> : </td>

                <td>@Model.Customer.Name</td>
            </tr>
            @*<tr>
                <td>Invoice No</td>
                <td> : </td>

                <td>@Model.InvoiceNo</td>
            </tr>*@
        </tbody>
    </table>
</div>
<br /><br />
<div class="adv-table">
    <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="myTable">
        <thead>
            <tr class="text-center">
                <td>SL</td>
                <td>Product</td>
                <td>Quantity</td>
                <td>MRP</td>
                <td>Total MRP</td>
            </tr>
        </thead>
        <tbody>
            @{
                int sl = 0;
                double grandTotal = 0;
                double discountPercentage = 0;
                double discountAmmount = 0;
                double payableAmmount = 0;
            }
            @foreach (var sd in Model.SalesDetailses)
            {
                grandTotal += sd.MRP * sd.Quantity;

                if (grandTotal > 1000)
                {
                    discountPercentage = Model.DiscountPercentage;
                }

                discountAmmount = (grandTotal * discountPercentage) / 100;
                payableAmmount = grandTotal - discountAmmount;

                <tr>
                    <td>@(++sl)</td>
                    <td>@sd.Product.Name</td>
                    <td class="text-right">@sd.Quantity</td>
                    <td class="text-right">@sd.MRP/-</td>
                    <td class="text-right">@(sd.MRP * sd.Quantity)/-</td>
                </tr>
            }

        </tbody>
        <tfoot>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td class="text-right">Grand Total</td>
                <td class="text-right">@grandTotal/-</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td class="text-right">Discount Ammount</td>
                <td class="text-right">- (@discountPercentage%)   @discountAmmount/-</td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td class="text-right">Payable Ammount</td>
                <td class="text-right">= @payableAmmount/-</td>
            </tr>
        </tfoot>
    </table>
</div>

RecycleBin/RecycleBin/Views/Sales/ViewSalesReport.cshtml
@using RecycleBin.Models
@model RecycleBin.Models.SalesViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-lg-12">
        <div class="text-center">
            <h3>Sales Report</h3>
        </div>
        <div class="adv-table">
            <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="myTable">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Date</th>
                        <th>Customer</th>
                        <th>Details</th>
                    </tr>
                </thead>
                @{ int sl = 0;}
                <tbody>
                    @foreach (var sales in Model.Saleses)
                    {
                        <tr>
                            <td>@(++sl)</td>
                            <td>@sales.Date.ToShortDateString()</td>
                            <td>@sales.Customer.Name</td>
                            <td>@Html.ActionLink("Details", "ViewSalesDetails", "Sales", new { salesId = sales.Id}, null)</td>
                            @*<td><button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#myModal">Details</button></td>*@
                        </tr>
                    }
                </tbody>

            </table>
        </div>

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <div class="modal-title" id="myModalLabel">Purchase Details</div>
                    </div>
                    <div class="modal-body">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-1.8.0.min.js"></script>
<script>
    $(document).ready(function () {

    });
</script>