RecycleBin/RecycleBin/Models/CustomerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using RecycleBin.Model.Model;

namespace RecycleBin.Models
{
    public class CustomerViewModel
    {
        public int ID { set; get; }

        [Required]
        [MaxLength(4, ErrorMessage = "Code must be 4 charecter")]
        [MinLength(4, ErrorMessage = "Code must be 4 charecter")]
        public string Code { set; get; }

        [Required(ErrorMessage = "Please Enter your Name")]
        [MaxLength(30, ErrorMessage = "Maximum 30 Charecter")]
        public string Name { set; get; }


        public string Address { set; get; }

        [Required(ErrorMessage = "Please Enter Contact Number")]
        [MaxLength(15,ErrorMessage = "Please Enter Valid Contact")]
        public string Contact { set; get; }

        [Required(ErrorMessage = "Please Enter your E-mail")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "Please Enter a valid Email")]
        public string Email { set; get; }

        [Required(ErrorMessage = "Please Enter Loyality point")]
        [Display(Name = "Loyalty Point")]
        public int LoyalityPoint { set; get; }

        public List<Customer> Customers { set; get; }

        public CustomerViewModel()
        {
            Customers = new List<Customer>();
        }
    }
}

RecycleBin/RecycleBin/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using RecycleBin.Manager.Manager;
using RecycleBin.Model.Model;
using RecycleBin.Models;

namespace RecycleBin.Controllers
{
    public class CustomerController : Controller
    {
        CustomerManager _customerManager = new CustomerManager();

        [HttpGet]
        public ActionResult Add()
        {
            CustomerViewModel customerViewModel = new CustomerViewModel();
            customerViewModel.Customers = _customerManager.GetAll();
            return View(customerViewModel);
        }

        [HttpPost]
        public ActionResult Add(CustomerViewModel customerViewModel)
        {
            Customer customer = Mapper.Map<Customer>(customerViewModel);
            string message = "";
            if (ModelState.IsValid)
            {
                if (_customerManager.Add(customer))
                {
                    message = "Customer Added Successfully";
                }
                else
                {
                    message = "Failed";
                }
            }
            else
            {
                ViewBag.ModelStateMessage = "Model State Faile";
            }

            ViewBag.Message = message;
            customerViewModel.Customers = _customerManager.GetAll();
            return View(customerViewModel);
        }
    }
}

RecycleBin/RecycleBin/Views/Shared/Customer/_customerDetails.cshtml
@model RecycleBin.Models.CustomerViewModel

<div class="row">
    <div class="col-lg-12">
        <div class="text-center">
            <h4>Customers Details</h4>
        </div>

        <div class="row">
            <div class="col-lg-8"></div>
            <div class="col-lg-4 form-group">
                <div class="input-group custom-search-form">
                    <input id="myInput" type="text" class="form-control" placeholder="Search by Name or Code">
                    <span class="input-group-btn">
                        <button class="btn btn-info" type="button">
                            <i class="fa fa-search"></i>
                        </button>
                    </span>
                </div>
            </div>
            <br />
        </div>

        <div class="adv-table">
            <table cellpadding="0" cellspacing="0" border="0" class="display table table-bordered" id="myTable">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Code</th>
                        <th>Name</th>
                        <th>Address</th>
                        <th>Contact</th>
                        <th>E-mail</th>
                        <th>Loyality Point</th>
                        <th>Action</th>
                    </tr>
                </thead>
                @{ int sl = 0;}
                <tbody>
                    @foreach (var customer in Model.Customers)
                    {
                        <tr>
                            <td>@(++sl)</td>
                            <td>@customer.Code</td>
                            <td>@customer.Name</td>
                            <td>@customer.Address</td>
                            <td>@customer.Contact</td>
                            <td>@customer.Email</td>
                            <td>@customer.LoyalityPoint</td>
                            <td>@Html.ActionLink("Edit", "Edit", "Customer", new { id = customer.Id }, null)</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script src="~/Scripts/jquery-1.8.0.min.js"></script>

<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tbody tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>